# Generated by Django 5.2.7 on 2025-10-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_blogs',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='blog.blog'),
        ),
    ]
