# Generated by Django 5.2.7 on 2025-10-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=10),
        ),
    ]
